name: Deploy Switchboard Staging

on:
  push:
    branches: [main, feat/documentDrive]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release API to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_API_NAME }}
          dockerfile_directory: ./api
          dockerfile_name: Dockerfile
          process_type: web
      - name: Build, Push and Release Frontend to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_NAME }}
          dockerfile_directory: ./
          dockerfile_name: frontend/Dockerfile
          process_type: web
      - name: Build, Push and Release Wundergraph to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_WGRAPH_NAME }}
          dockerfile_directory: ./
          dockerfile_name: frontend/Dockerfile
          process_type: web
      # - name: Build, Push and Release NGINX to Heroku. # Your custom step name
      #   uses: gonuit/heroku-docker-deploy@v1.3.3
      #   with:
      #     email: ${{ secrets.HEROKU_EMAIL }}
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: ${{ secrets.HEROKU_FRONTEND_NAME }}
      #     dockerfile_directory: ./nginx
      #     dockerfile_name: Dockerfile
      #     process_type: web
